// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3M9Wwlce5oGwPQo3FYUK-jRbM6DTPB8I',
    appId: '1:481583811571:web:633cb36127f894a0936086',
    messagingSenderId: '481583811571',
    projectId: 'chatting-app-37131',
    authDomain: 'chatting-app-37131.firebaseapp.com',
    storageBucket: 'chatting-app-37131.firebasestorage.app',
    measurementId: 'G-FYXEGST8C8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtuvKaI5ET5lz53pYhbbBVbZt8ICEGJ3A',
    appId: '1:481583811571:android:97daf3f1b022a9c0936086',
    messagingSenderId: '481583811571',
    projectId: 'chatting-app-37131',
    storageBucket: 'chatting-app-37131.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANg0w_V8JE0XK6Rf8AOu3pjZIoN7BBkq0',
    appId: '1:481583811571:ios:74c030a7c213bfc3936086',
    messagingSenderId: '481583811571',
    projectId: 'chatting-app-37131',
    storageBucket: 'chatting-app-37131.firebasestorage.app',
    iosBundleId: 'com.example.graduationProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyANg0w_V8JE0XK6Rf8AOu3pjZIoN7BBkq0',
    appId: '1:481583811571:ios:74c030a7c213bfc3936086',
    messagingSenderId: '481583811571',
    projectId: 'chatting-app-37131',
    storageBucket: 'chatting-app-37131.firebasestorage.app',
    iosBundleId: 'com.example.graduationProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA3M9Wwlce5oGwPQo3FYUK-jRbM6DTPB8I',
    appId: '1:481583811571:web:b010f83c56ab5335936086',
    messagingSenderId: '481583811571',
    projectId: 'chatting-app-37131',
    authDomain: 'chatting-app-37131.firebaseapp.com',
    storageBucket: 'chatting-app-37131.firebasestorage.app',
    measurementId: 'G-5PFQD0CL0Y',
  );
}
